[project]
name = "polder"
version = "0.0.3"
description = "Arrays with DataFrame axis labels"
readme = "README.md"
authors = [{ name = "Nardi Lam", email = "mail@nardilam.nl" }]
requires-python = ">=3.11"
dependencies = [
    "array-api-compat==1.11.2",
    "array-api-extra>=0.7.2",
    "immutabledict>=4.3.1",
    "narwhals>=2.18.1",
    "numpy>=2.4.4",
    "ordered-set>=4.1.0",
    "types-array-api>=1.1.4",
    "typing-extensions>=4.15.0",
]

[build-system]
requires = ["uv_build>=0.11.2,<0.12"]
build-backend = "uv_build"

[dependency-groups]
dev = ["polars>=1.39.3", "pytest>=9.0.2", "jax>=0.10.0"]

[tool.ruff.format]
preview = true

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]
ignore = ["E731"]

[tool.pytest]
addopts = ["--import-mode=importlib"]
