from collections.abc import Mapping, Sequence
from typing import Any, Generic, Protocol, Self, TypeAlias, TypeVar

from narwhals import DataFrame, Expr
from optype.numpy import Array1D, CanArray

AnyDataFrame: TypeAlias = DataFrame[Any]


class AnyArray(CanArray, Protocol):
    """A protocol that value array types have to satisfy.."""


LabelFrameType = TypeVar("LabelFrameType", bound=AnyDataFrame, covariant=True)
ValueArrayType = TypeVar("ValueArrayType", bound=AnyArray, covariant=True)


ArrayAxisIndices: TypeAlias = int | slice | list[int] | Array1D
AxisIndices: TypeAlias = ArrayAxisIndices | Expr

Scalar: TypeAlias = int | float | complex | bool

AxisLabelsSpecifier: TypeAlias = Sequence[str]
AxisLabelsToPivot: TypeAlias = AxisLabelsSpecifier | Sequence[AxisLabelsSpecifier]
AxesSlice = tuple[int, int]


class FrameLabeledArray(Generic[LabelFrameType, ValueArrayType], Protocol):
    def values(self, *indices: ArrayAxisIndices) -> ValueArrayType:
        """The value array that is being labeled. Can be any type that supports
        the Array API. Allows Numpy-style indexing to return a part of the
        array, which may be more efficient."""
        ...

    def labels(
        self, axis: int | slice | None = None
    ) -> LabelFrameType | None | Sequence[LabelFrameType | None]:
        """The labels for the value array. There is one frame per axis of the
        array, so `len(labels) == len(values.shape)`. If an axis has size 1, it
        may be unlabeled, represented by `None`. Allows returning labels for
        only a part of the axes, which may be more efficient."""
        ...

    def shape(self) -> Sequence[int]:
        """The shape of the array."""
        ...

    def __getitem__(self, indices: AxisIndices | tuple[AxisIndices, ...]) -> Self:
        """Index the array, either using numerical indices, or using Narwhals
        expressions which will be used to filter the labels."""
        ...

    def equals(self, other: Self, /) -> bool: ...

    def pivot(
        self,
        /,
        *,
        axis_labels_to_pivot: Mapping[int, AxisLabelsToPivot],
        fill_value: Any = ...,
    ) -> Self: ...

    def unpivot(
        self,
        /,
        *,
        axes_to_merge: Sequence[AxesSlice],
    ) -> Self: ...

    # Arithmetic operators
    def __abs__(self, /) -> Self: ...
    def __pos__(self, /) -> Self: ...
    def __neg__(self, /) -> Self: ...
    def __add__(self, other: Self | Scalar, /) -> Self: ...
    def __radd__(self, other: Self | Scalar, /) -> Self: ...
    def __sub__(self, other: Self | Scalar, /) -> Self: ...
    def __rsub__(self, other: Self | Scalar, /) -> Self: ...
    def __mul__(self, other: Self | Scalar, /) -> Self: ...
    def __rmul__(self, other: Self | Scalar, /) -> Self: ...
    def __truediv__(self, other: Self | Scalar, /) -> Self: ...
    def __rtruediv__(self, other: Self | Scalar, /) -> Self: ...
    def __floordiv__(self, other: Self | Scalar, /) -> Self: ...
    def __rfloordiv__(self, other: Self | Scalar, /) -> Self: ...
    def __mod__(self, other: Self | Scalar, /) -> Self: ...
    def __rmod__(self, other: Self | Scalar, /) -> Self: ...
    def __pow__(self, other: Self | Scalar, /) -> Self: ...
    def __rpow__(self, other: Self | Scalar, /) -> Self: ...

    # Matrix multiplication
    def __matmul__(self, other: Self, /) -> Self: ...

    # Bitwise operators
    def __invert__(self, /) -> Self: ...
    def __and__(self, other: Self | Scalar, /) -> Self: ...
    def __rand__(self, other: Self | Scalar, /) -> Self: ...
    def __or__(self, other: Self | Scalar, /) -> Self: ...
    def __ror__(self, other: Self | Scalar, /) -> Self: ...
    def __xor__(self, other: Self | Scalar, /) -> Self: ...
    def __rxor__(self, other: Self | Scalar, /) -> Self: ...
    def __lshift__(self, other: Self | Scalar, /) -> Self: ...
    def __rlshift__(self, other: Self | Scalar, /) -> Self: ...
    def __rshift__(self, other: Self | Scalar, /) -> Self: ...
    def __rrshift__(self, other: Self | Scalar, /) -> Self: ...

    # Comparison operators
    def __lt__(self, other: Self | Scalar, /) -> Self: ...
    def __le__(self, other: Self | Scalar, /) -> Self: ...
    def __gt__(self, other: Self | Scalar, /) -> Self: ...
    def __ge__(self, other: Self | Scalar, /) -> Self: ...
    # Apparently __eq__ is supposed to return boolean, does Numpy break this rule too?
    def __eq__(self, other: Self | Scalar, /) -> Self: ...  # type: ignore
    def __ne__(self, other: Self | Scalar, /) -> Self: ...  # type: ignore


AnyFrameLabeledArray: TypeAlias = FrameLabeledArray[AnyDataFrame, AnyArray]

SomeFrameLabeledArray = TypeVar("SomeFrameLabeledArray", bound="AnyFrameLabeledArray")
